# Development Environment Configuration
# Relaxed settings for local development
# Smaller connection pools for resource-constrained dev machines

[default]
# ============================================================================
# CONNECTION POOL OPTIMIZATIONS - DEVELOPMENT
# ============================================================================
# Database Connection Pool (Neo4j) - Smaller for dev
db_pool_min_size = 1          # Minimal for single developer
db_pool_max_size = 4          # Small pool for development
db_pool_idle_timeout = 600    # 10 minutes (shorter for dev)
db_pool_connect_timeout = 30  # 30 seconds for faster feedback
db_pool_health_check_interval = 30  # 30 seconds for dev

# Redis Connection Pool - Minimal for dev
redis_pool_min_size = 1       # Single connection for dev
redis_pool_max_size = 3       # Small cache pool
redis_pool_idle_timeout = 180 # 3 minutes
redis_pool_connect_timeout = 15 # 15 seconds
redis_pool_health_check_interval = 30 # 30 seconds

# HTTP Connection Pool (TWS) - Minimal for dev
http_pool_min_size = 1        # Single connection for testing
http_pool_max_size = 5        # Small pool for dev TWS calls
http_pool_idle_timeout = 180  # 3 minutes
http_pool_connect_timeout = 5 # 5 seconds for fast feedback
http_pool_health_check_interval = 30 # 30 seconds

# ============================================================================
# DEVELOPMENT ENVIRONMENT SETTINGS
# ============================================================================
environment = "development"
log_level = "DEBUG"           # Full debug logging
server_host = "127.0.0.1"     # Localhost only
server_port = 8000            # Standard dev port

# Development security (relaxed)
admin_username = "admin"
cors_allowed_origins = ["http://localhost:3000", "http://localhost:3001", "http://localhost:5173"]
tws_verify = false             # Disable SSL for easier dev setup
tws_ca_bundle = null

# Mock mode for development
tws_mock_mode = true           # Use mock TWS for development

# Cache settings - smaller for dev
cache_hierarchy_l1_max_size = 1000  # Smaller cache for dev
cache_hierarchy_l2_ttl = 300        # 5 minutes TTL for dev
enable_cache_swr = false            # Disable complex features in dev
enable_cache_mutex = false          # Disable for simpler dev experience

# Rate limiting - very relaxed for dev
rate_limit_public_per_minute = 1000
rate_limit_authenticated_per_minute = 10000
rate_limit_critical_per_minute = 100

# Enable all migrations for testing
MIGRATION_ENABLE_METRICS = true
MIGRATION_USE_NEW_CACHE = true
MIGRATION_USE_NEW_TWS = true
MIGRATION_USE_NEW_RATE_LIMIT = true

# ============================================================================
# DEVELOPMENT TESTING FEATURES
# ============================================================================
# Memory bounds - smaller for dev machines
robust_cache_max_memory_mb = 64     # 64MB cache limit for dev
robust_cache_max_items = 10000      # 10K items limit

# Connection monitoring - relaxed thresholds for dev
pool_utilization_warning_threshold = 0.9   # 90% utilization warning
pool_utilization_critical_threshold = 0.95 # 95% utilization critical
connection_wait_time_warning_ms = 200      # 200ms wait time warning
connection_wait_time_critical_ms = 1000    # 1000ms wait time critical

# Development-specific features
enable_debug_endpoints = true
enable_test_endpoints = true
mock_external_services = true       # Mock external services in dev
enable_performance_logging = true
enable_connection_pool_logging = true  # Extra logging for pool debugging

# ============================================================================
# DEVELOPMENT DATABASE SETTINGS
# ============================================================================
# Use local/test databases
neo4j_uri = "neo4j://127.0.0.1:7687"
redis_url = "redis://localhost:6379/0"

# Backup disabled in development
backup_enabled = false
health_check_interval_seconds = 60     # Less frequent in dev
health_check_timeout_seconds = 5       # Faster timeout for dev
health_check_failure_threshold = 2     # More lenient in dev