# LiteLLM Configuration for Resync TWS Application
# This configuration defines model routing rules and provider settings
# for OpenRouter API usage

model_list:
  # Primary OpenRouter model - Tongyi DeepResearch
  - model_name: "tongyi-deepresearch"
    litellm_params:
      model: "alibaba/tongyi-deepresearch-30b-a3b:free"
      api_key: "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"
      api_base: "https://openrouter.ai/api/v1"
      temperature: 0.7
      max_tokens: 4096

  # Fallback OpenRouter model
  - model_name: "openrouter-fallback"
    litellm_params:
      model: "meta-llama/llama-3.2-3b-instruct:free"
      api_key: "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"
      api_base: "https://openrouter.ai/api/v1"
      temperature: 0.5
      max_tokens: 2048

# Model aliases for easier referencing in code
model_aliases:
  "tws-troubleshooting": "tongyi-deepresearch"
  "tws-basic-query": "openrouter-fallback"
  "tws-research": "tongyi-deepresearch"
  "tws-general": "openrouter-fallback"

# Router settings for model selection
router_settings:
  # Model group aliases for different use cases
  model_group_alias:
    - {group_name: "tws-general", list_of_model_names: ["openrouter-fallback", "tongyi-deepresearch"]}
    - {group_name: "tws-troubleshooting", list_of_model_names: ["tongyi-deepresearch", "openrouter-fallback"]}
    - {group_name: "tws-research", list_of_model_names: ["tongyi-deepresearch", "openrouter-fallback"]}

  # Default fallback settings
  fallbacks:
    - {type: "model", fallbacks: ["openrouter-fallback", "tongyi-deepresearch"]}
  
  # Timeout settings
  timeout: 600  # 10 minutes for complex TWS operations

# Custom settings for TWS-specific usage
general_settings:
  # Enable caching for faster repeated queries
  cache:
    type: "redis"  # Use Redis for distributed caching
    host: "{APP_REDIS_URL}"
    enabled: true
  
  # Enable detailed logging for debugging
  master_key: "{APP_LITELLM_MASTER_KEY}"  # Optional security measure
  
  # Cost tracking
  database_url: "{APP_DATABASE_URL}"  # For storing usage analytics